log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

initial-networks:
  disable: true
  data:
    - name: polygon
      chain_id: 1
      rpc_url: rpc_url
      ws_url: websocket_url
      factory_address: factory_address
      factory_name: factory_name
      factory_version: factory_version
      first_block: 1
      native_token_name: token_name
      native_token_symbol: t
    - name: ether
      chain_id: 2
      rpc_url: rpc_url
      ws_url: websocket_url
      factory_address: factory_address
      factory_name: factory_name
      factory_version: factory_version
      first_block: 1
      native_token_name: token_name
      native_token_symbol: t

connector:
  url: http://traefik/integrations
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHg0MDk3NDhkZmIzMWNhMTQyNGQxMzE2NjM5MThjN2E0NWYyZWE2NTA3IiwicHVycG9zZSI6InNlc3Npb24iLCJleHAiOjMyODY4MDU0NzR9.5Z7FBn4UrgjaNNOGSy0j98cb3M9san4A8kvGzq98Fsg

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: network-svc
  service_port: 80
